version: 2.1
jobs:
  build:
    machine:
      true
    steps:
      - checkout
  test:
    machine:
      true
      # image: circleci/classic:2017-01
    steps:
      - run: python setup.py test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
