version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    # machine:
      # true
      # image: circleci/classic:2017-01
    steps:
      - checkout
      - run: python setup.py test